name: Publish package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    if: github.repository == 'hsorby/vue3-sphinx-xml'
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for --provenance
      contents: read   # for actions/checkout
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
      - run: yarn install
      - run: yarn build-package
      - name: Determine npm tag
        id: determine_tag
        run: |
          # If the git tag (e.g., v1.0.0-beta.0) contains a hyphen, it's a prerelease.
          if [[ "${{ github.ref_name }}" == *-* ]]; then
            echo "tag=next" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi
      - run: npm publish --provenance --ignore-scripts --tag ${{ steps.determine_tag.outputs.tag }}
